classes: 1000000
data_type: "npy"
in_channels: 1
train_dataset_dir: ""
val_dataset_dir: ""
save_dir: ""
pretrained_models: "./data/pretrained_models/"
validate_loss: True
xbm_enable: True
xbm_size: 10240
xbm_start_iteration: 5000
xbm_weight: 1.0
mixup_enable: True
mean_std_enable: False
# if not use xbm_mixup_alternate, set the value larger than total iterations
xbm_mixup_alternate: 2000
out_dimension: 512
input_dimension: 64
device: [0, 1, 2, 3]
batch_size: 2048
train_ratio: 0.7
val_ratio: 0.3
test_ratio: 0.0
invert_ratio: 0.0
num_workers: 8
epoch: 50
lr: 0.05
step_size: 10
gamma: 0.1
weight_decay: 0.005
left_right_flip: 0.0
up_down_flip: 0.0